import { Injectable, NotFoundException } from '@nestjs/common';
import { DepartmentRepository } from 'src/department/domain/repositories/department.repository';
import { UserRepository } from 'src/shared/repositories/user.repository';
import { Ticket } from 'src/tickets/domain/entities/ticket.entity';
import { TicketRepository } from 'src/tickets/domain/repositories/ticket.repository';

interface CreateTicketInput {
  departmentId: string;
  question: string;
  guestId?: string;
  userId?: string;
}

@Injectable()
export class CreateTicketUseCase {
  constructor(
    private readonly departmentRepo: DepartmentRepository,
    private readonly userRepo: UserRepository,
    private readonly ticketRepo: TicketRepository,
  ) {}

  async execute({
    departmentId,
    question,
    guestId,
    userId,
  }: CreateTicketInput) {
    if (!!guestId && !!userId) {
      guestId = undefined;
    }

    const ticket = await this.ticketRepo.save(
      Ticket.create({
        question,
        department: await this.departmentRepo
          .findById(departmentId)
          .then((dept) => {
            if (!dept) {
              throw new NotFoundException({
                departmentId: 'department_not_found',
              });
            }
            return dept;
          }),
        isAutoGenerated: false,
        user: userId
          ? await this.userRepo.findById(userId).then((user) => {
              if (!user) {
                throw new NotFoundException({ userId: 'user_not_found' });
              }
              return user;
            })
          : undefined,
        guestId,
      }),
    );

    return { ticket: ticket.ticketCode.toString() };
  }
}
