import { Injectable, NotFoundException } from '@nestjs/common';
import { DepartmentRepository } from 'src/department/domain/repositories/department.repository';
import { GuestRepository } from 'src/guest/domain/repositories/guest.repository';
import { Ticket } from 'src/tickets/domain/entities/ticket.entity';
import { TicketRepository } from 'src/tickets/domain/repositories/ticket.repository';
import { FilesService } from 'src/files/domain/services/files.service';
import { CloneAttachmentUseCase } from 'src/files/application/use-cases/clone-attachment.use-case';

interface CreateTicketInput {
  departmentId: string;
  question: string;
  guestId?: string;
  attach?: boolean;
  chooseAttachments?: string[];
}

@Injectable()
export class CreateTicketUseCase {
  constructor(
    private readonly departmentRepo: DepartmentRepository,
    private readonly ticketRepo: TicketRepository,
    private readonly guestRepo: GuestRepository,
    private readonly filesService: FilesService,
    private readonly cloneAttachmentUseCase: CloneAttachmentUseCase,
  ) {}

  async execute({
    departmentId,
    question,
    guestId,
    attach,
    chooseAttachments,
  }: CreateTicketInput) {
    const ticket = await this.ticketRepo.save(
      await Ticket.create({
        question,
        department: await this.departmentRepo
          .findById(departmentId)
          .then((dept) => {
            if (!dept) {
              throw new NotFoundException({
                departmentId: 'department_not_found',
              });
            }
            return dept;
          }),
        isAutoGenerated: false,
        guest: await this.guestRepo.findById(guestId),
      }),
    );

    const uploadKey = attach
      ? await this.filesService.genUploadKey(
          ticket.id.toString(),
          undefined,
          guestId,
        )
      : undefined;

    // Clone attachments if provided
    if (chooseAttachments && chooseAttachments.length > 0) {
      await this.cloneAttachmentUseCase.execute({
        attachmentIds: chooseAttachments,
        targetId: ticket.id.toString(),
      });
    }

    return { ticket: ticket.ticketCode.toString(), uploadKey };
  }
}
