import { Injectable, NotFoundException } from '@nestjs/common';
import { DepartmentRepository } from 'src/department/domain/repositories/department.repository';
import { GuestRepository } from 'src/guest/domain/repositories/guest.repository';
import { Ticket } from 'src/tickets/domain/entities/ticket.entity';
import { TicketRepository } from 'src/tickets/domain/repositories/ticket.repository';
import { FilesService } from 'src/files/domain/services/files.service';

interface CreateTicketInput {
  departmentId: string;
  question: string;
  guestId?: string;
  attach?: boolean;
}

@Injectable()
export class CreateTicketUseCase {
  constructor(
    private readonly departmentRepo: DepartmentRepository,
    private readonly ticketRepo: TicketRepository,
    private readonly guestRepo: GuestRepository,
    private readonly filesService: FilesService,
  ) {}

  async execute({ departmentId, question, guestId, attach }: CreateTicketInput) {
    const ticket = await this.ticketRepo.save(
      await Ticket.create({
        question,
        department: await this.departmentRepo
          .findById(departmentId)
          .then((dept) => {
            if (!dept) {
              throw new NotFoundException({
                departmentId: 'department_not_found',
              });
            }
            return dept;
          }),
        isAutoGenerated: false,
        guest: await this.guestRepo.findById(guestId),
      }),
    );

    const uploadKey = attach
      ? await this.filesService.genUploadKey(ticket.id.toString())
      : undefined;

    return { ticket: ticket.ticketCode.toString(), uploadKey };
  }
}
