import { Department } from 'src/department/domain/entities/department.entity';
import { User } from 'src/shared/entities/user.entity';
import { UUID } from 'src/shared/value-objects/uuid.vo';
import { TicketCode } from '../value-objects/ticket-code.vo';
import {
  TicketStatus,
  TicketStatusEnum,
} from '../value-objects/ticket-status.vo';
import { Point } from 'src/shared/entities/point.entity';
import { Answer } from './answer.entity';

export interface TicketCreateRaw {
  id?: string | UUID;
  user?: User;
  guestId?: string | UUID;
  question: string;
  department: Department;
  ticketCode?: string | TicketCode;
  status?: TicketStatus | TicketStatusEnum;
  point?: Point;
  pointId?: string;
  isAutoGenerated?: boolean;
  answer?: Answer;
  createdAt?: Date;
  updatedAt?: Date;
}

export class Ticket {
  private readonly _id: UUID;
  private _user?: User;
  private _guestId?: UUID;
  private _question: string;
  private _department: Department;
  private readonly _ticketCode: TicketCode;
  private _status: TicketStatus;
  private _point?: Point;
  private _pointId?: string;
  private _isAutoGenerated: boolean;
  private _answer?: Answer;
  private _createdAt: Date;
  private _updatedAt: Date;

  private constructor(options: {
    id: UUID;
    user?: User;
    guestId?: UUID;
    question: string;
    department: Department;
    ticketCode?: TicketCode;
    status?: TicketStatus;
    point?: Point;
    pointId?: string;
    isAutoGenerated?: boolean;
    answer?: Answer;
    createdAt?: Date;
    updatedAt?: Date;
  }) {
    this._id = options.id;
    this._user = options.user;
    this._guestId = options.guestId;
    this._question = options.question;
    this._department = options.department;
    this._ticketCode = options.ticketCode ?? TicketCode.create();
    this._status = options.status ?? TicketStatus.create();
    this._point = options.point;
    this._pointId = options.pointId;
    this._isAutoGenerated = options.isAutoGenerated ?? true;
    this._answer = options.answer;
    this._createdAt = options.createdAt ?? new Date();
    this._updatedAt = options.updatedAt ?? new Date();
  }

  static create(raw: TicketCreateRaw): Ticket {
    const id = raw.id instanceof UUID ? raw.id : UUID.create(raw.id);
    const guestId = raw.guestId
      ? raw.guestId instanceof UUID
        ? raw.guestId
        : UUID.create(raw.guestId)
      : undefined;
    const ticketCode =
      raw.ticketCode instanceof TicketCode
        ? raw.ticketCode
        : raw.ticketCode
          ? TicketCode.create(raw.ticketCode)
          : undefined;
    const status =
      raw.status instanceof TicketStatus
        ? raw.status
        : typeof raw.status === 'number'
          ? TicketStatus.create(raw.status)
          : undefined;

    return new Ticket({
      id,
      user: raw.user,
      guestId,
      question: raw.question,
      department: raw.department,
      ticketCode,
      status,
      point: raw.point,
      pointId: raw.pointId,
      isAutoGenerated: raw.isAutoGenerated,
      answer: raw.answer,
      createdAt: raw.createdAt,
      updatedAt: raw.updatedAt,
    });
  }

  // Getters
  get id(): UUID {
    return this._id;
  }

  get user(): User | undefined {
    return this._user;
  }

  get guestId(): UUID | undefined {
    return this._guestId;
  }

  get question(): string {
    return this._question;
  }

  get department(): Department {
    return this._department;
  }

  get ticketCode(): TicketCode {
    return this._ticketCode;
  }

  get status(): TicketStatus {
    return this._status;
  }

  get point(): Point | undefined {
    return this._point;
  }

  get pointId(): string | undefined {
    return this._pointId;
  }

  get isAutoGenerated(): boolean {
    return this._isAutoGenerated;
  }

  get answer(): Answer | undefined {
    return this._answer;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  // Setters
  set user(user: User | undefined) {
    this._user = user;
    this._updatedAt = new Date();
  }

  set guestId(guestId: UUID | undefined) {
    this._guestId = guestId;
    this._updatedAt = new Date();
  }

  set question(question: string) {
    this._question = question;
    this._updatedAt = new Date();
  }

  set department(department: Department) {
    this._department = department;
    this._updatedAt = new Date();
  }

  set status(status: TicketStatusEnum) {
    this._status = TicketStatus.create(status);
    this._updatedAt = new Date();
  }

  set point(point: Point | undefined) {
    this._point = point;
    this._pointId = point?.id.value;
    this._updatedAt = new Date();
  }

  set pointId(pointId: string | undefined) {
    this._pointId = pointId;
    this._point = undefined;
    this._updatedAt = new Date();
  }

  set answer(answer: Answer | undefined) {
    this._answer = answer;
    this._updatedAt = new Date();
  }

  set isAutoGenerated(value: boolean) {
    this._isAutoGenerated = value;
    this._updatedAt = new Date();
  }

  // Utility methods
  public updatePoint(newPoint: Point): void {
    this.point = newPoint;
  }

  public addAnswer(answer: Answer): void {
    this.answer = answer;
  }

  public removeAnswer(): void {
    this.answer = undefined;
  }

  public toPersistence() {
    return {
      id: this._id.toString(),
      userId: this._user?.id.toString(),
      guestId: this._guestId?.toString(),
      question: this._question,
      departmentId: this._department.id.toString(),
      ticketCode: this._ticketCode.value,
      status: this._status.value,
      pointId: this._pointId,
      isAutoGenerated: this._isAutoGenerated,
      createdAt: this._createdAt,
      updatedAt: this._updatedAt,
    };
  }
}
